
spring.application.name=${appName}
server.port=${port}

server.servlet.context-path=/${basePath}
app.version=${version}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuracion Datasource POSTGRESQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/
spring.datasource.username=username
spring.datasource.password=password

#Configuracion Security
security.app.jwtSecret= secretA45sx1D23D3DASD3D3DWDWDWADAFGF+++234SXX++DS323++32+
security.app.jwtExpirationMs=86400000

## For test
security.app.jwtRefreshExpirationMs= 180000
springdoc.show-login-endpoint=true