
spring.output.ansi.enabled=ALWAYS
logging.level.root=WARN
logging.level.es.upm.miw=DEBUG

spring.data.mongodb.uri=mongodb+srv://alvarochavez:ppFtWAJzr4Bhvq1l@restgen-mongodb.irql7yl.mongodb.net/restgen-db?retryWrites=true&w=majority&appName=restgen-mongodb

#JWT  -----------------------------------------------------
restgen.jwt.secret=secretdev