
spring.output.ansi.enabled=ALWAYS
logging.level.root=DEBUG

spring.data.mongodb.uri=mongodb+srv://alvarochavez%3AppFtWAJzr4Bhvq1l%40restgen-mongodb.irql7yl.mongodb.net%2Frestgen-db%3FretryWrites%3Dtrue%26w%3Dmajority%26appName%3Drestgen-mongodb

#JWT  -----------------------------------------------------
restgen.jwt.secret=secretdev