spring.application.name=generator
spring.profiles.active=local

#JWT  -----------------------------------------------------
restgen.jwt.expire=36000
restgen.jwt.issuer=es-restgen-miw

server.servlet.contextPath=/restgen