name: CD - GitHub Docker Packages & Deploy AWS ECS

on:
  push:
    branches: [develop]

env:
  REPOSITORY: ${{ github.repository }}
  GHCR_URL: ghcr.io  # GitHub Container Registry
  AWS_ECR_URL: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
  MONGODB_URI: ${{ secrets.MONGODB_URI }}

jobs:
  cd:
    name: Build & Push GitHub Package & Deploy on AWS ECS
    runs-on: ubuntu-22.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
          cache: maven

      - name: Extract version from pom.xml
        id: get-version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Normalize repository name
        run: echo "REPOSITORY=$(echo ${{ env.REPOSITORY }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build project and package JAR
        run: |
          mvn -f generator/pom.xml clean package -DskipTests
          ls -l generator/target/

      - name: Debug Environment Variables
        run: echo "MongoDB URI= ${{ secrets.MONGODB_URI }}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PERSONAL_ACCESS_TOKEN }}

      - name: Build & Push Docker image to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.GHCR_URL }}/${{ env.REPOSITORY }}:${{ env.VERSION }}
            ${{ env.GHCR_URL }}/${{ env.REPOSITORY }}:latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Docker image to AWS ECR
        run: |
          docker build -t $AWS_ECR_URL/$REPOSITORY:$VERSION -t $AWS_ECR_URL/$REPOSITORY:latest .
          docker push $AWS_ECR_URL/$REPOSITORY:$VERSION
          docker push $AWS_ECR_URL/$REPOSITORY:latest

      - name: Update ECS service
        run: |
          aws ecs update-service --cluster devops-cluster --service deployed-aws-ecs-service --force-new-deployment
